### PR TITLE
Fix RSN parsing

### LINKED ISSUE #115: Display name scraping picking up HTML tags
I noticed that my bot started storing malformed display names containing HTML img tags. I looked into it, and the OSRS hiscores page now shows a trophy icon next to a player's name if they were in the top 100 overall pre-sailing ([example](https://secure.runescape.com/m=hiscore_oldschool/overall?category_type=0)). This appears to be getting picked up when your util scrapes the page for names.

For example, the result of `getRSNFormat('fast_07')` now returns `''`

If you inspect the row for a player with this icon, it looks something like this:

```HTML
<tr class="personal-hiscores__row personal-hiscores__row--type-highlight">
  <td class="right">
    <a href="https://secure.runescape.com/m=hiscore_oldschool/pre-sailing-overall?table=0&amp;user=FasT 07">
      <img class="miniimg" src="https://www.runescape.com/img/rsp777/title2/trophy.png" title="Ranked 37 overall pre-Sailing addition">
    </a>
  </td>
  <td class="right">1</td>
  <td class="left">
    <a href="hiscorepersonal?user1=FasT 07">FasT 07</a>
  </td>
  <td>
    2,376
  </td>
  <td class="right">
    4,642,325,575
  </td>
</tr>
```

Since the `getRSNFormat` function scrapes the element using this query...
```js
const anchor = dom.window.document.querySelector(
  '.personal-hiscores__row.personal-hiscores__row--type-highlight a'
);
```
It makes sense that it's picking up the first `<a>`, which for these players would be the `` tag itself.

### PR DESCRIPTION
**Pull request by maxswa**
Fixes #115

### CODE REVIEW

File: src/hiscores.ts [hunk 1]
```diff
@@ -98,11 +100,19 @@ export async function getRSNFormat(
...
-      return rsnFromElement(anchor);
+    if (row) {
+      const { innerHTML } = row ?? {};
+      return (
+        innerHTML?.match(
+          new RegExp(
+            rsn.replace(WHITESPACE_REGEX, WHITESPACE_REGEX_STRING),
+            'gi'
+          )
+        )?.[0] ?? rsn
```
Comment (maxswa) [inline src/hiscores.ts:114]: Some more robust rsn parsing that will hopefully be more resilient in the face of future changes to the HTML of the hiscores.
